### ISSUE TITLE
alice.org System Requirements to include Windows 10.

### ISSUE THREAD

**Issue by justingeeslin** [TheAliceProject/alice3#146]
I noticed the [System Requirements](https://www.alice.org/get-alice/alice-3/) for Windows make no mention of Windows 10. 

> Windows (XP, Vista 32-bit, Vista 64-bit, Windows 7 32-bit, Windows 7 64-bit, Windows 8 32-bit, Windows 8 64-bit (thanks pcwiz84 for Win8 info))

Its a pretty exhaustive list otherwise which made me wonder if there was Windows 10 support. I can see that there is Windows 10 support based on the nearby [Installing Alice 3 page](http://alice3.pbworks.com/w/page/57581183/Download%20And%20Install).

Maybe Windows 10 (32 & 64 bit) should be included in the list?

**Comment by dabeshouse** [comment]
Windows 10 has been added to the System Requirements. Thanks for noticing
