### ISSUE TITLE
Alice 3 Tools link in README is broken

### ISSUE THREAD

**Issue by pratikpc** [TheAliceProject/alice3#169]
https://github.com/TheAliceProject/alice3-tools

[Link here](https://github.com/TheAliceProject/alice3/blob/develop/README.md#development-tools)

**Comment by dabeshouse** [comment]
The tools repository has not been made public yet.
Its contents require some review and updating before that can be done. Until that time is found I should probably make that clear in the read me.
Thanks for catching this.
