### ISSUE TITLE
isCollidingWith not working as expected?

### ISSUE THREAD

**Issue by sbrito** [TheAliceProject/alice3#277]
We are trying to call isCollidingWith in the walk procedure written for the penguin and it's not working? Are we missing something in the bounding boxes here?

[penguinKickAnswer.a3p.zip](https://github.com/TheAliceProject/alice3/files/9444769/penguinKickAnswer.a3p.zip)

**Comment by dabeshouse** [comment]
You are not missing anything.
My apologies, but there are a few bugs in the collision code in the 3.6.0.2 release.

Alice 3.7 is in final testing and will be available for download very soon. (Hopefully this week)
I tested your world there and it works much better.

Daniel Abeshouse
Developer, Bug Maker, and Bug Fixer for the Alice Project

**Comment by dabeshouse** [comment]
OK, two weeks
Try your world in Alice 3.7 - https://www.alice.org/get-alice/alice-3/

**Comment by dabeshouse** [comment]
Fixed in 3.7.0.0. Closing.
