### ISSUE TITLE
Small UI Bug

### ISSUE THREAD

**Issue by everythingability** [TheAliceProject/alice3#280]
Hi...

If I run my project, the window shows. Then if I tweak project setting/code etc, the Run window is behind my Project window and still running (but I can't change any variables etc because my project is running).

I think the Run window needs to be modal. I know students will get stuck with this.

I'm on Monterey Mac btw and Alice 3 latest. 

LOVING the project though!

**Comment by everythingability** [comment]
Hang on.. I'M getting caught by this all the time... :-)

**Comment by dabeshouse** [comment]
The lost run window is a problem.
In an earlier version Alice forced the run window to the front, but this caused problems with certain dialogs (error reports, among others) leaving Alice in an unusable state that could only be killed by the system.
We are discussing options.

**Comment by dabeshouse** [comment]
PR https://github.com/TheAliceProject/alice3/pull/284 keeps the run window in front of the main window, but not all windows, so the lock up with an error dialog is prevented. It also increases the size, which makes it harder to lose, and I think was long overdue.
