### ISSUE TITLE
Alice 3 issues with macOS Ventura 13.0

### ISSUE THREAD

**Issue by sbrito** [TheAliceProject/alice3#285]
The Alice 3 installer is not working on macOS Ventura 13.0. The student has Alice 3 installed already and tried deleting and reinstalling, but the installer isn't working. The student cannot run any code in Alice 3. When they tried to run things, the window with the running program doesn't come up

**Comment by dabeshouse** [comment]
What version of Alice are they trying to install?
[3.7.0.0](https://www.alice.org/get-alice/alice-3/) is the first version of Alice with a certificate, which Ventura may require. 3.7.0.0 was released last month.

**Comment by Sabit04** [comment]
I'm the student, just an update. I had Alice 3 installed before and updated the Mac to MacOs Ventura. Opening the code works fine, but when I try to run the code, it doesn't show up. I deleted it and reinstalled the latest version and that doesn't work either. I can't finish the installation process as the application just freezes

**Comment by MelanieLam** [comment]
A solution that worked for another student was disabling 'dark mode' which is a display/appearance setting.

**Comment by dabeshouse** [comment]
The Install4J version we use on the build systems should be updated since they have a fix for the Ventura dark mode bug in version 10.

**Comment by jspiegel3** [comment]
> The Install4J version we use on the build systems should be updated since they have a fix for the Ventura dark mode bug in version 10.

Hi my students  are having the same issue as well  running Ventura 13 on Mac.  I do not see Install4J only the builds through 3, would you mind linking for me ?  This when they download from alice.org thank you

**Comment by MelanieLam** [comment]
Jspiegel- the short term solution is to disable dark mode in system preferences. This should allow the installation to progress as normal. We will be updating Install4j in our next release (not out yet!)
